apiVersion: apps/v1
kind: Deployment
metadata:
  name: ysrcp-deployment
  labels:
    app: ysrcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ysrcp
  template:
    metadata:
      labels:
        app: ysrcp
    spec:
      containers:
      - name: ysrcp-container
        image: jithendragurram/ysrcp-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ysrcp-service
spec:
  selector:
    app: ysrcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
